<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\KbArticle;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Seeds 5 KB articles per department (25 total) using the new
 * department-based categorization (v1.5). Each article is published
 * and visible to everyone so agents can exercise the KB UI.
 */
class KbArticleDemoSeeder extends Seeder
{
    public function run(): void
    {
        $author = User::where('email', 'admin@confipetrol.local')->first();

        $articles = [
            // ── TI ────────────────────────────────────────────────────
            'ti' => [
                ['Cómo resetear tu contraseña de Windows', 'Guía paso a paso para restablecer la contraseña de tu cuenta de Windows corporativa.\n\n## Pasos\n\n1. Presiona Ctrl+Alt+Supr\n2. Selecciona "Cambiar contraseña"\n3. Ingresa tu contraseña actual\n4. Ingresa tu nueva contraseña (mínimo 8 caracteres, mayúscula, número)\n5. Confirma la nueva contraseña\n\n## Políticas de contraseña\n\n- Mínimo 12 caracteres\n- Al menos 1 mayúscula, 1 minúscula, 1 número, 1 símbolo\n- No puede ser igual a las últimas 3 contraseñas\n- Expira cada 90 días'],
                ['Conectarse a la VPN corporativa (FortiClient)', 'Para trabajar desde casa necesitas conectarte a la VPN de Confipetrol.\n\n## Instalación\n\n1. Descarga FortiClient desde el portal de TI\n2. Instala como administrador\n3. Abre FortiClient y ve a "VPN remota"\n\n## Configuración\n\n- Servidor: `vpn.confipetrol.com`\n- Puerto: `443`\n- Usuario: tu correo corporativo\n- Contraseña: la misma de Windows\n\n## Troubleshooting\n\nSi no conecta, verifica:\n- Internet funcionando (prueba abrir google.com)\n- No estés en otra VPN (desconecta ProtonVPN, NordVPN, etc.)\n- Hora del sistema correcta (problema común)'],
                ['Configurar correo corporativo en el móvil', 'Para recibir correos de @confipetrol.com en tu teléfono, usa Microsoft Outlook.\n\n## iOS\n\n1. Descarga Microsoft Outlook de la App Store\n2. Agregar cuenta de correo\n3. Ingresa: tu_usuario@confipetrol.com\n4. Ingresa tu contraseña de Windows\n5. Acepta permisos de MDM\n\n## Android\n\nPasos idénticos a iOS usando Google Play Store.\n\n## Políticas\n\nAl configurar correo corporativo debes aceptar:\n- PIN obligatorio\n- Borrado remoto si pierdes el dispositivo\n- Encriptación del almacenamiento'],
                ['Mi impresora no imprime — qué hacer', 'Antes de crear un ticket, sigue estos pasos.\n\n## Diagnóstico rápido\n\n1. **Verifica papel y tóner** — la impresora no lo dice a veces\n2. **Reinicia la impresora** (apagar 30 seg y volver a encender)\n3. **Verifica la conexión**: cable o WiFi encendido\n4. **Prueba imprimir una página de prueba** desde el panel de la impresora\n\n## Desde Windows\n\n1. Panel de Control → Dispositivos e impresoras\n2. Click derecho en tu impresora → Ver lo que se está imprimiendo\n3. Impresora → Cancelar todos los documentos\n4. Vuelve a imprimir\n\n## Si nada funciona\n\nCrea un ticket en soporte con:\n- Modelo de la impresora\n- Ubicación (oficina / piso)\n- Mensaje de error exacto'],
                ['Cómo instalar Microsoft Teams', 'Teams es la herramienta oficial para reuniones y chat.\n\n## Descarga oficial\n\nSolo descarga desde: https://teams.microsoft.com/downloads\n\n## Instalación Windows\n\n1. Ejecuta el instalador\n2. Inicia sesión con tu correo @confipetrol.com\n3. Permite notificaciones\n\n## Primera sesión\n\n- Revisa que tu micrófono y cámara funcionen (ícono de configuración)\n- Configura tu foto de perfil\n- Únete a los canales de tu equipo\n\n## Problemas comunes\n\n- **No abre**: reinstala como administrador\n- **No hay audio**: verifica permisos en Configuración de Privacidad\n- **Pantalla negra en reuniones**: actualiza drivers de GPU'],
            ],

            // ── RRHH ──────────────────────────────────────────────────
            'rrhh' => [
                ['Cómo solicitar vacaciones', 'Las vacaciones se solicitan con 15 días de anticipación.\n\n## Requisitos\n\n- Haber completado al menos 1 año en la empresa\n- No tener tickets disciplinarios abiertos\n- Coordinar con tu jefe directo\n\n## Proceso\n\n1. Ingresa al portal de RRHH\n2. Solicitud de vacaciones\n3. Selecciona las fechas (mínimo 5 días hábiles)\n4. Agrega el motivo\n5. Envía a aprobación\n\n## Aprobación\n\n- Jefe directo aprueba primero\n- RRHH verifica disponibilidad\n- Recibes confirmación por correo'],
                ['Entender mi recibo de nómina', 'El recibo llega cada 15 y 30 del mes.\n\n## Componentes del recibo\n\n- **Salario base**: tu sueldo mensual\n- **Horas extras**: pagadas al 25% extra L-V, 75% fin de semana\n- **Auxilio de transporte**: si ganas menos de 2 SMMLV\n- **Prima de servicios**: junio y diciembre\n- **Cesantías**: febrero\n\n## Deducciones\n\n- Salud (EPS): 4% del salario\n- Pensión (AFP): 4% del salario\n- Retención en la fuente: según tabla DIAN\n- Otras (préstamos, libranzas)\n\n## Descarga del PDF\n\nEn el portal de RRHH → Mis recibos → Descargar'],
                ['Incapacidades médicas — cómo reportar', 'Si tienes una incapacidad médica, avisa de inmediato.\n\n## Plazos\n\n- **Primeras 2 horas**: avisar verbalmente al jefe\n- **Primeras 24 horas**: subir la incapacidad al portal\n- **Máximo 48 horas**: entregar el original en RRHH\n\n## Documentos necesarios\n\n1. Certificado de incapacidad (EPS)\n2. Historia clínica (opcional)\n3. Formato de autorización (si es superior a 3 días)\n\n## Proceso de pago\n\n- Días 1-2: los paga la empresa\n- Día 3 en adelante: los paga la EPS (demora 30-60 días)\n- La empresa anticipa y luego cobra a la EPS\n\n## Importante\n\nSi no reportas en 48 horas, se considera inasistencia injustificada.'],
                ['Certificados laborales', 'Certificados laborales para bancos, universidades, etc.\n\n## Tipos disponibles\n\n- **Simple**: indica cargo y tiempo\n- **Con salario**: agrega el salario actual\n- **Con funciones**: detalla funciones del cargo\n- **En inglés**: para trámites internacionales\n\n## Solicitud\n\n1. Portal RRHH → Certificados\n2. Seleccionar tipo\n3. Indicar destinatario (entidad)\n4. Enviar solicitud\n\n## Tiempos\n\n- Certificado simple: 1 día hábil\n- Con salario: 2 días\n- En inglés: 3-5 días\n\nEl PDF se descarga firmado digitalmente.'],
                ['Afiliación a EPS y AFP', 'Al ingresar a la empresa debes afiliarte a salud (EPS) y pensión (AFP).\n\n## EPS (Salud)\n\nOpciones actuales: Sura, Sanitas, Compensar, Famisanar, Nueva EPS.\n\n### Proceso\n1. Escoge tu EPS (puedes mantener la actual si ya tenías empleo)\n2. Llena formulario en portal RRHH\n3. Firma autorización de descuento\n\n## AFP (Pensión)\n\nOpciones: Porvenir, Colpensiones, Protección, Old Mutual.\n\n### Recomendación\n- Si tienes <40 años: AFP privada (Porvenir, Protección, Old Mutual)\n- Si tienes >45 años: Colpensiones\n- Entre 40-45: consultar asesor\n\n## Tu primer pago\n\nEl primer aporte se descuenta del primer salario. Verás el desglose en tu recibo.'],
            ],

            // ── Compras ───────────────────────────────────────────────
            'compras' => [
                ['Cómo hacer una solicitud de compra', 'Todo gasto mayor a $500.000 requiere ticket en el área de compras.\n\n## Información requerida\n\n- Descripción clara del producto\n- Cantidad y unidad (ej: 3 unidades, 5 metros)\n- Especificaciones técnicas mínimas\n- Proveedor sugerido (opcional)\n- Presupuesto estimado\n- Centro de costo al que imputar\n\n## Adjuntos útiles\n\n- Cotizaciones (mínimo 2 si el monto supera $2M)\n- Ficha técnica del producto\n- Justificación del uso\n\n## Aprobaciones\n\n- < $2M: jefe de área\n- $2M - $10M: jefe + gerencia\n- > $10M: comité de compras\n\n## Tiempo\n\n- Urgente: 48h\n- Normal: 5-10 días hábiles\n- Con importación: 30-60 días'],
                ['Proveedores aprobados — cómo encontrarlos', 'Solo se compra a proveedores aprobados en el sistema.\n\n## Dónde consultar\n\nPortal → Compras → Catálogo de proveedores\n\n## Filtros disponibles\n\n- Por categoría (oficina, tecnología, limpieza, etc.)\n- Por ubicación (Bogotá, regional, internacional)\n- Por rating interno (estrellas de 1-5)\n\n## Cómo proponer un nuevo proveedor\n\n1. Crea un ticket en "Proveedores"\n2. Adjunta:\n   - Cámara de comercio\n   - RUT actualizado\n   - Certificación de pagos al sistema (ARL, EPS, Pensión)\n   - 2 referencias comerciales\n3. El área de Compras valida en 5-10 días\n\n## Urgencias\n\nSi necesitas un proveedor no listado por urgencia, marca el ticket como "Crítica" y explica el caso.'],
                ['Cómo cotizar con múltiples proveedores', 'Para montos >$2M se requieren mínimo 2 cotizaciones.\n\n## Proceso estándar\n\n1. Define especificaciones iguales para todos los proveedores\n2. Envía solicitud por correo (template en Compras)\n3. Plazo mínimo: 3 días hábiles para responder\n4. Compara: precio, tiempo de entrega, garantía, soporte\n\n## Matriz de comparación\n\nUsa la matriz del portal para evaluar:\n- Precio (40% del peso)\n- Tiempo entrega (20%)\n- Calidad (20%)\n- Garantía / soporte (20%)\n\n## Qué NO hacer\n\n- No revelar el precio de un proveedor a otro\n- No tener proveedores "fantasma" (una cotización real + 2 falsas)\n- No cotizar si tienes conflicto de interés con algún proveedor\n\n## Aprobación\n\nLa matriz se adjunta al ticket de compra. El comité decide el ganador.'],
                ['Política de inventario de oficina', 'Artículos de oficina (papel, tóner, útiles) manejan stock mínimo.\n\n## Quién administra\n\nAuxiliar administrativo del piso / sede.\n\n## Artículos comunes\n\n- Papel A4: caja de 10 resmas\n- Tóner impresora: 2 cartuchos de repuesto\n- Esferos, lápices, borradores: 1 caja por piso\n- Carpetas, folders: según consumo\n\n## Reposición automática\n\nCuando el stock llega al 30%, el auxiliar genera ticket automático.\n\n## Solicitar algo específico\n\n1. Portal → Compras → Solicitud de papelería\n2. Especifica artículo y cantidad\n3. Justifica si supera el límite normal\n\n## Auditorías\n\nCada 6 meses se audita el inventario. Mantén el orden en tu piso.'],
                ['Trámite de facturas y pagos a proveedores', 'Proceso de radicación de facturas.\n\n## Requisitos para que una factura sea pagada\n\n1. **Factura electrónica vigente** (DIAN 2020+)\n2. **Orden de compra** previa emitida por el sistema\n3. **Remisión firmada** por quien recibió el bien/servicio\n4. **Certificaciones**: ARL, Salud, Pensión, Parafiscales al día\n\n## Dónde se radica\n\nPortal → Compras → Radicar factura (proveedor) — o en físico en recepción.\n\n## Tiempo de pago\n\n- Pago a 30 días desde radicación (default)\n- Pago a 45 días (convenios especiales)\n- Pago anticipado solo con aprobación de gerencia\n\n## Problemas comunes\n\n- Factura sin orden de compra previa → se rechaza\n- Documentos de SS vencidos → se pausa el pago\n- Precio distinto al cotizado → se devuelve para ajustar\n\n## Consulta de estado\n\nPortal → Mis facturas (proveedor) — ves el estado en tiempo real.'],
            ],

            // ── Mantenimiento ─────────────────────────────────────────
            'mantenimiento' => [
                ['Reportar una falla en infraestructura', 'Para reportar problemas con la oficina (aires, luces, baños, etc.).\n\n## Cómo reportar\n\n1. Portal → Mantenimiento → Nuevo reporte\n2. Categoría: Mantenimiento locativo\n3. Ubicación exacta (piso, área, sala)\n4. Descripción del problema\n5. Foto si es posible\n\n## Tipos de falla\n\n- **Urgente** (2 horas): fugas de agua, corto circuitos, cristales rotos\n- **Alta** (24 horas): aires acondicionados, ascensores\n- **Media** (3 días): luces fundidas, puertas\n- **Baja** (1 semana): pintura, muebles\n\n## Contacto directo para emergencias\n\nEn caso de emergencia real (inundación, incendio) llamar **inmediatamente** al 601-XXX-XXXX sin esperar ticket.\n\n## Seguimiento\n\nEl técnico actualiza el ticket al llegar, durante el trabajo y al finalizar.'],
                ['Mantenimiento preventivo programado', 'Cada equipo/instalación tiene cronograma preventivo.\n\n## Equipos cubiertos\n\n- Aires acondicionados: cada 3 meses\n- Plantas eléctricas: cada 6 meses\n- Ascensores: mensual\n- Sistemas de seguridad: cada 3 meses\n- Extintores: cada 6 meses\n- Detectores de humo: cada año\n\n## Notificación previa\n\nRecibes correo 48 horas antes de cada mantenimiento.\n\n## Qué esperar durante el mantenimiento\n\n- Interrupciones de energía programadas (aviso previo)\n- Ruido breve\n- Restricción de áreas (ej: ascensor fuera de servicio 2 horas)\n\n## Cómo consultar el cronograma\n\nPortal → Mantenimiento → Calendario de mantenimientos.\n\n## Retrasos\n\nSi un mantenimiento se posterga, recibes notificación con la nueva fecha.'],
                ['Cómo solicitar mobiliario o traslado', 'Cambios de ubicación, muebles nuevos, traslados internos.\n\n## Tipos de solicitud\n\n### Traslado de puesto\n- Mínimo 5 días de anticipación\n- Especifica: desde / hacia / qué mover (silla, mueble, computador, teléfono)\n- Coordinar con TI para la parte tecnológica\n\n### Mobiliario nuevo\n- Adjuntar justificación\n- Presupuesto aprobado por jefe\n- Seleccionar de catálogo de proveedores aprobados\n\n### Ergonomía\n- Requiere evaluación previa de Salud Ocupacional\n- Sillas ergonómicas: prescripción médica + evaluación\n- Monitores extra: justificación técnica\n\n## Plazos\n\n- Traslado interno: 3-5 días\n- Mobiliario nuevo (stock): 1 semana\n- Mobiliario nuevo (a pedido): 4-8 semanas\n\n## Importante\n\nNo muevas muebles pesados por cuenta propia. Hay personal entrenado.'],
                ['Gestión de aires acondicionados', 'Problemas más comunes con los aires.\n\n## Antes de reportar\n\n1. Verifica el control remoto (baterías nuevas?)\n2. Revisa la temperatura configurada (22-24°C es lo normal)\n3. Verifica que la ventana esté cerrada\n4. Comprueba si otros en el piso tienen el mismo problema\n\n## Cuándo crear ticket\n\n- No enfría / no calienta\n- Gotea agua\n- Hace ruidos extraños\n- Huele mal (hongos)\n- Control remoto perdido\n\n## Limpieza programada\n\nCada 3 meses se limpian filtros. No hay que pedirlo.\n\n## Temperatura estándar\n\n- Invierno: 22-24°C\n- Verano: 20-22°C\n- Oficinas con mucha gente: 21°C\n\n## Si quieres cambiar la temp\n\nConsulta con tus compañeros de área y manda ticket con la propuesta. El área caliente / fría se aprueba en conjunto.'],
                ['Seguridad y salud en el trabajo', 'Normas básicas de seguridad en la oficina.\n\n## Emergencias\n\n- **Incendio**: evacuación por escaleras al punto de encuentro (parqueadero)\n- **Sismo**: triángulo de vida bajo escritorio\n- **Accidente**: primeros auxilios en piso 1, contactar brigada\n\n## Brigadistas del edificio\n\nLista actualizada en cada piso. Busca el cartel amarillo.\n\n## Equipos de emergencia\n\n- Extintores: uno por cada 100m²\n- Detectores de humo: en todos los pasillos\n- Rociadores: en áreas de alto riesgo\n- Señalización de rutas de evacuación\n\n## Simulacros\n\n- Evacuación: 2 veces al año (abril y octubre)\n- Incendio: 1 vez al año\n- Sismo: según cronograma Alcaldía\n\n## Reportar riesgos\n\nCrea ticket si identificas:\n- Cables sueltos\n- Pisos con desnivel\n- Equipos sin conexión a tierra\n- Áreas mal iluminadas\n\nNo es denuncia, es prevención.'],
            ],

            // ── Operaciones ───────────────────────────────────────────
            'operaciones' => [
                ['Procedimiento de apertura y cierre de turno', 'Para operadores en turno, apertura/cierre del shift.\n\n## Apertura de turno\n\n1. Llegar 15 min antes\n2. Verificar EPP (casco, botas, guantes)\n3. Firmar bitácora de entrada\n4. Recibir turno del operario saliente (novedades, pendientes)\n5. Inspección visual del área\n6. Verificar equipos operativos\n\n## Durante el turno\n\n- Registrar toda novedad en bitácora\n- Reportar inmediatamente cualquier falla\n- Mantener comunicación con radio\n- No dejar el puesto sin relevo\n\n## Cierre de turno\n\n1. Completar bitácora\n2. Entregar turno al siguiente operario\n3. Firmar salida\n4. Dejar equipos en estado operativo\n5. Reportar novedades al supervisor\n\n## Documentos obligatorios\n\n- Bitácora física firmada\n- Registro en sistema SCADA (si aplica)\n- Reporte de consumos (combustibles, materiales)'],
                ['Gestión documental operativa', 'Toda documentación operativa sigue este flujo.\n\n## Tipos de documentos\n\n- Procedimientos operativos (PON)\n- Instructivos de trabajo\n- Manuales de equipos\n- Listas de chequeo\n- Registros de operación\n\n## Dónde se guardan\n\nSharePoint → Operaciones → [Planta]\n\n## Control de versiones\n\n- Solo la versión oficial publicada se usa en operación\n- Versiones antiguas quedan en histórico\n- Cambios requieren aprobación del jefe de operaciones\n\n## Cuándo crear ticket\n\n- Propuesta de cambio a procedimiento\n- Documento desactualizado\n- Nuevo equipo sin documentación\n- Solicitud de capacitación\n\n## Auditorías\n\n- Internas: cada 3 meses\n- ISO 9001: anual\n- Clientes: según contrato\n\n## Importante\n\nNunca operes con procedimiento desactualizado. Si dudas, pregunta.'],
                ['Protocolo de paradas de planta', 'Paradas programadas y no programadas.\n\n## Parada programada\n\n### Planificación (2 meses antes)\n1. Cronograma detallado\n2. Lista de trabajos\n3. Recursos requeridos\n4. Proveedores externos coordinados\n\n### Antes de la parada (1 semana)\n- Verificar todos los materiales\n- Confirmar llegada de contratistas\n- Briefing con operadores\n\n### Durante\n- Seguir cronograma al minuto\n- Registrar avances cada hora\n- Coordinar con seguridad y salud\n\n### Reinicio\n- Pruebas escalonadas\n- Validación de controles\n- Liberación por operaciones\n\n## Parada no programada\n\n1. Identificar causa\n2. Aislar el equipo\n3. Notificar jefe + operaciones + mantenimiento\n4. Evaluar impacto en producción\n5. Estimar tiempo de reparación\n6. Coordinar reinicio\n\n## Reportes\n\nTodo evento queda en el sistema de gestión operativa con análisis de causa raíz (RCA).'],
                ['Logística de entrada y salida de materiales', 'Proceso para recibir y despachar materiales.\n\n## Entrada de materiales\n\n1. Proveedor llega a portería con factura/remisión\n2. Se verifica con la orden de compra\n3. Inspección visual y cuantitativa\n4. Muestreo de calidad (si aplica)\n5. Traslado a bodega\n6. Registro en sistema (ERP)\n7. Informe a Compras\n\n## Salida de materiales\n\n### A planta\n- Solicitud formal del operario\n- Vale firmado\n- Entrega por almacenista\n- Registro de salida\n\n### A clientes / terceros\n- Orden de despacho\n- Guía de transporte\n- Factura (si aplica)\n- Foto del material cargado\n- Firma de conductor\n\n## Inventario\n\n- Cíclico: diario por zona\n- Completo: mensual\n- Auditorías externas: semestral\n\n## Herramientas\n\nERP + códigos de barras + lectoras. Nada se mueve sin escanear.'],
                ['Reporte de novedades operativas', 'Cómo reportar novedades del día.\n\n## Qué es una novedad\n\nCualquier evento que impacte la operación normal:\n- Parada no programada\n- Accidente o casi-accidente\n- Cambio de personal en turno\n- Condiciones anormales (clima, visitas)\n- Pedido especial de cliente\n- Falla de equipo\n- Reserva de stock baja\n\n## Cuándo reportar\n\n- **Urgente**: inmediato por radio + ticket en 1 hora\n- **Importante**: ticket en 4 horas\n- **Informativa**: al final del turno\n\n## Estructura del reporte\n\n1. **Qué pasó** (hechos, no opiniones)\n2. **Cuándo** (hora exacta)\n3. **Dónde** (equipo, área)\n4. **Quién** (involucrados)\n5. **Impacto** (producción, seguridad, calidad)\n6. **Acciones tomadas**\n7. **Próximos pasos**\n\n## Reporte diario de producción\n\nSe envía al final del turno:\n- Toneladas producidas\n- Consumos\n- Paradas\n- Rendimiento vs meta'],
            ],
        ];

        foreach ($articles as $deptSlug => $dept_articles) {
            $dept = Department::where('slug', $deptSlug)->first();
            if (! $dept) {
                continue;
            }

            foreach ($dept_articles as [$title, $body]) {
                $article = KbArticle::updateOrCreate(
                    ['slug' => Str::slug($title)],
                    [
                        'title' => $title,
                        'body' => str_replace('\\n', "\n", $body),
                        'department_id' => $dept->id,
                        'status' => 'published',
                        'visibility' => 'public',
                    ],
                );

                // author_id y published_at están fuera de $fillable por
                // protección anti mass-assignment; se setean via forceFill.
                $article->forceFill([
                    'author_id' => $author?->id,
                    'published_at' => now()->subDays(rand(1, 30)),
                ])->save();
            }
        }
    }
}
