<?php

namespace Database\Seeders;

use App\Enums\TicketImpact;
use App\Enums\TicketUrgency;
use App\Models\Category;
use App\Models\TicketTemplate;
use Illuminate\Database\Seeder;

/**
 * Seeds 5 ticket templates per department (25 total) for demo.
 */
class TicketTemplateDemoSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // ── TI ────────────────────────────────────────────────────
            ['ti-hardware', 'Solicitud de equipo nuevo', 'Solicitud de computador para nuevo empleado', "Empleado: [NOMBRE]\nCargo: [CARGO]\nFecha de inicio: [FECHA]\nÁrea: [ÁREA]\n\nTipo de equipo requerido:\n- [ ] Laptop estándar (oficina)\n- [ ] Laptop gama alta (desarrollo / diseño)\n- [ ] Desktop\n- [ ] Monitor adicional\n\nAccesorios:\n- [ ] Mouse\n- [ ] Teclado\n- [ ] Auriculares\n- [ ] Base para laptop\n\nPerfiles de software:\n- [ ] Estándar (Office, Outlook, Teams)\n- [ ] Desarrollo (IDE, Docker, etc.)\n- [ ] Diseño (Adobe Suite)\n- [ ] Específico: [describir]", TicketImpact::Bajo, TicketUrgency::Media],
            ['ti-cuentas-y-accesos', 'Alta de usuario Azure AD', 'Crear cuenta de usuario para nuevo empleado', "Empleado: [NOMBRE]\nDocumento: [CC]\nCorreo propuesto: [nombre.apellido@confipetrol.com]\nCargo: [CARGO]\nJefe inmediato: [JEFE]\nFecha de ingreso: [FECHA]\n\nGrupos de Azure requeridos:\n- [ ] Todos (default)\n- [ ] Agentes de soporte\n- [ ] Supervisores\n- [ ] Administración\n- [ ] Área específica: [indicar]\n\nAccesos requeridos:\n- [ ] Correo @confipetrol.com\n- [ ] Microsoft 365 (Teams, OneDrive)\n- [ ] VPN corporativa\n- [ ] Helpdesk\n- [ ] Otros: [listar]", TicketImpact::Medio, TicketUrgency::Alta],
            ['ti-software', 'Instalación de software corporativo', 'Solicitud de licencia e instalación', "Empleado: [NOMBRE]\nCorreo: [correo]\nEquipo: [hostname o serial]\n\nSoftware solicitado: [NOMBRE SOFTWARE]\nVersión: [versión]\nMotivo de uso: [justificar]\n\n¿Requiere licencia comercial?\n- [ ] Sí (adjuntar aprobación de Compras)\n- [ ] No (software free/open-source)\n\n¿Requiere permisos de administrador local?\n- [ ] Sí (indicar duración)\n- [ ] No\n\nFecha requerida: [FECHA]", TicketImpact::Bajo, TicketUrgency::Media],
            ['ti-correo-y-teams', 'Recuperación de correo borrado', 'Restaurar correos eliminados permanentemente', "Usuario: [correo@confipetrol.com]\nFecha aproximada del borrado: [FECHA]\nAsunto o remitente del correo: [detalles]\n\n¿Está en la carpeta de Elementos eliminados?\n- [ ] Sí (se puede recuperar fácil)\n- [ ] No (requiere backup)\n\nImportancia: [razonar si es urgente]\n\nNota: los correos solo se pueden recuperar hasta 30 días después del borrado.", TicketImpact::Medio, TicketUrgency::Media],
            ['ti-redes-y-wifi', 'Problema de conectividad de red', 'Sin acceso a internet o a recursos de red', "Ubicación (piso, oficina): [ubicación]\nEquipo (hostname/serial): [equipo]\n\n¿Qué funciona y qué no?\n- [ ] No hay internet\n- [ ] Hay internet pero no accede a [sistema interno]\n- [ ] WiFi no conecta\n- [ ] WiFi conecta pero muy lento\n- [ ] Cable funciona, WiFi no\n\n¿Otros compañeros tienen el mismo problema?\n- [ ] Sí\n- [ ] No\n- [ ] No sé\n\nPruebas ya realizadas:\n- [ ] Reinicio del equipo\n- [ ] Reinicio del router\n- [ ] Cambio de red WiFi\n- [ ] Ejecución de ipconfig/release+renew", TicketImpact::Alto, TicketUrgency::Alta],

            // ── RRHH ──────────────────────────────────────────────────
            ['rrhh-nomina', 'Solicitud de certificado laboral', 'Certificado laboral para entidad externa', "Tipo de certificado:\n- [ ] Simple (cargo y tiempo)\n- [ ] Con salario actual\n- [ ] Con funciones\n- [ ] En inglés\n\nEntidad destinataria: [BANCO / ENTIDAD]\nDirigido a: [destinatario específico, opcional]\n\nFecha requerida: [FECHA]\n\n¿Requiere apostille o traducción notariada?\n- [ ] Sí\n- [ ] No", TicketImpact::Bajo, TicketUrgency::Baja],
            ['rrhh-vacaciones', 'Solicitud de vacaciones', 'Solicitud formal de vacaciones', "Empleado: [NOMBRE]\nCédula: [CC]\n\nFechas solicitadas:\n- Desde: [FECHA INICIO]\n- Hasta: [FECHA FIN]\n- Días hábiles: [cantidad]\n\n¿Días hábiles pendientes por tomar?: [X días]\n\nMotivo: [opcional]\n\n¿Quién te reemplazará?: [NOMBRE reemplazo]\n\nHe coordinado con mi jefe directo:\n- [ ] Sí\n- [ ] No", TicketImpact::Bajo, TicketUrgency::Baja],
            ['rrhh-contratos', 'Modificación de contrato', 'Cambio de cargo, salario o condiciones', "Empleado: [NOMBRE]\nCédula: [CC]\n\nTipo de modificación:\n- [ ] Cambio de cargo\n- [ ] Aumento salarial\n- [ ] Cambio de jornada\n- [ ] Cambio de sede\n- [ ] Otro: [especificar]\n\nCargo actual: [CARGO ACTUAL]\nCargo nuevo: [CARGO NUEVO]\n\nSalario actual: [$]\nSalario nuevo: [$]\n\nFecha efectiva del cambio: [FECHA]\n\nJustificación: [motivar la solicitud]\n\nAprobado por:\n- [ ] Jefe directo\n- [ ] Gerencia de área\n- [ ] Gerencia General (si aplica)", TicketImpact::Medio, TicketUrgency::Media],
            ['rrhh-nomina', 'Incapacidad médica', 'Reportar incapacidad temporal', "Empleado: [NOMBRE]\nCédula: [CC]\nCargo: [CARGO]\n\nFechas de incapacidad:\n- Desde: [FECHA]\n- Hasta: [FECHA]\n- Total días: [N días]\n\nEPS: [NOMBRE EPS]\nCódigo de diagnóstico (CIE): [si lo tienes]\n\nAdjuntos:\n- [ ] Certificado original de incapacidad\n- [ ] Historia clínica (opcional)\n\n¿Es prórroga?\n- [ ] Sí (ticket original: TK-YYYY-NNNNN)\n- [ ] No", TicketImpact::Medio, TicketUrgency::Alta],
            ['rrhh-afiliaciones', 'Cambio de EPS o AFP', 'Cambiar entidad de salud o pensión', "Empleado: [NOMBRE]\nCC: [CC]\n\nTipo de cambio:\n- [ ] EPS\n- [ ] AFP\n- [ ] Caja de compensación\n- [ ] ARL\n\nEntidad actual: [ACTUAL]\nEntidad nueva: [NUEVA]\n\nMotivo del cambio:\n- [ ] Mala atención\n- [ ] Beneficios\n- [ ] Recomendación personal\n- [ ] Otro\n\n¿Ya realizaste el trámite en la nueva entidad?:\n- [ ] Sí (adjuntar comprobante)\n- [ ] No (cuándo planeas hacerlo)", TicketImpact::Bajo, TicketUrgency::Baja],

            // ── Compras ───────────────────────────────────────────────
            ['compras-solicitud-de-compra', 'Compra de equipos de oficina', 'Solicitud de mobiliario y papelería', "Artículo(s) solicitados:\n1. [nombre] — cantidad: [X]\n2. [nombre] — cantidad: [X]\n3. ...\n\nÁrea solicitante: [ÁREA]\nCentro de costo: [CÓDIGO CC]\n\nUso: [justificar]\n\nFecha requerida: [FECHA]\n\nPresupuesto estimado: $[MONTO]\n\n¿Tienes proveedor sugerido?:\n- [ ] Sí: [NOMBRE PROVEEDOR]\n- [ ] No, que Compras cotice\n\nAdjuntos:\n- [ ] Cotización\n- [ ] Ficha técnica\n- [ ] Aprobación de jefe", TicketImpact::Bajo, TicketUrgency::Media],
            ['compras-cotizaciones', 'Cotización de software/licencias', 'Solicitud de cotización de software comercial', "Software: [NOMBRE]\nFabricante: [FABRICANTE]\nVersión: [versión]\n\nTipo de licencia:\n- [ ] Perpetua\n- [ ] Suscripción anual\n- [ ] Suscripción mensual\n- [ ] Por usuario\n- [ ] Por servidor/CPU\n\nCantidad de licencias: [N]\n\nUsuarios destino:\n- [ ] Equipos específicos: [listar]\n- [ ] Roles: [listar]\n\nPresupuesto aprobado: $[MONTO]\n\n¿Ya se usa una versión anterior?:\n- [ ] Sí, upgrade\n- [ ] No, compra nueva\n\nJustificación técnica: [describir]", TicketImpact::Medio, TicketUrgency::Media],
            ['compras-proveedores', 'Alta de nuevo proveedor', 'Registro de proveedor en el sistema', "Información del proveedor:\n- Razón social: [NOMBRE]\n- NIT: [NIT]\n- Dirección: [DIR]\n- Teléfono: [TEL]\n- Correo: [correo]\n- Contacto comercial: [NOMBRE CONTACTO]\n\nCategoría de bienes/servicios: [CATEGORÍA]\n\nDocumentos adjuntos:\n- [ ] Cámara de comercio (<3 meses)\n- [ ] RUT actualizado\n- [ ] Certificación pagos SS (ARL, EPS, Pensión)\n- [ ] Certificación bancaria\n- [ ] Referencias comerciales (mín 2)\n\nJustificación de por qué usar este proveedor: [razonar]", TicketImpact::Medio, TicketUrgency::Baja],
            ['compras-solicitud-de-compra', 'Compra urgente de consumibles', 'Solicitud urgente de papelería/tóner', "Artículos necesarios:\n- [ ] Tóner impresora [modelo]: [X unidades]\n- [ ] Papel A4: [X resmas]\n- [ ] Otros: [listar]\n\nImpacto de no tenerlo:\n- [ ] Planta parada\n- [ ] Oficina no imprime\n- [ ] Baja productividad\n- [ ] Otro\n\n¿Por qué es urgente?\n[motivar]\n\nFecha límite para tenerlo: [FECHA]\n\nCentro de costo: [CC]", TicketImpact::Alto, TicketUrgency::Alta],
            ['compras-solicitud-de-compra', 'Renovación de contrato con proveedor', 'Extender vigencia de contrato existente', "Proveedor: [NOMBRE]\nNIT: [NIT]\n\nContrato actual:\n- Número: [N° contrato]\n- Fecha vencimiento: [FECHA]\n- Valor anual: $[MONTO]\n- Objeto: [describir brevemente]\n\nPropuesta de renovación:\n- Nueva vigencia: [inicio → fin]\n- Nuevo valor: $[MONTO]\n- ¿Hay ajuste por IPC?: [sí/no]\n- ¿Se incluye nuevo alcance?: [describir]\n\n¿Evaluación del proveedor?\n- Rating interno: [1-5 estrellas]\n- Comentarios: [experiencia]\n\n¿Se cotizó competencia?:\n- [ ] Sí, 2+ cotizaciones adjuntas\n- [ ] No (justificar por qué se va con el mismo)", TicketImpact::Medio, TicketUrgency::Media],

            // ── Mantenimiento ─────────────────────────────────────────
            ['mantenimiento-mantenimiento-locativo', 'Reporte de fuga de agua', 'Fuga de agua en instalaciones', "Ubicación exacta:\n- Piso: [N]\n- Área: [oficina/baño/cocina/parqueadero]\n- Referencia: [cerca de qué objeto/mueble]\n\nTipo de fuga:\n- [ ] Goteo pequeño\n- [ ] Chorro constante\n- [ ] Inundación\n- [ ] Mancha en techo\n- [ ] Mancha en piso\n\nOrigen aparente:\n- [ ] Grifo\n- [ ] Tubería\n- [ ] Aire acondicionado\n- [ ] Inodoro\n- [ ] Desconocido\n\nImpacto:\n- [ ] Afecta paso de personas\n- [ ] Daño a equipos/muebles\n- [ ] Riesgo eléctrico cercano\n- [ ] Solo molestia\n\nAcción temporal tomada: [ej. balde, trapero]\n\n¡URGENTE! Si es inundación grave, llamar al 601-XXX-XXXX antes de crear ticket.", TicketImpact::Alto, TicketUrgency::Alta],
            ['mantenimiento-equipos', 'Aire acondicionado no enfría', 'Reporte de AA con falla', "Ubicación:\n- Piso: [N]\n- Oficina/Sala: [nombre]\n\nSíntoma:\n- [ ] No enciende\n- [ ] Enciende pero no enfría\n- [ ] Enfría poco\n- [ ] Hace ruido extraño\n- [ ] Gotea agua\n- [ ] Huele feo (hongos)\n- [ ] Control remoto no responde\n\nTemperatura seteada: [°C]\nTemperatura real percibida: [°C]\n\nHorario del problema:\n- [ ] Todo el día\n- [ ] Solo mañanas\n- [ ] Solo tardes\n- [ ] Intermitente\n\n¿Otros AAs del piso funcionan bien?\n- [ ] Sí\n- [ ] No\n- [ ] No sé", TicketImpact::Medio, TicketUrgency::Media],
            ['mantenimiento-mantenimiento-locativo', 'Cambio de luces o bombillos', 'Luces fundidas o parpadeando', "Ubicación:\n- Piso: [N]\n- Área: [oficina/pasillo/baño/parqueadero]\n- Referencia: [cerca de qué]\n\nCantidad de luces afectadas: [N]\n\nSíntoma:\n- [ ] No encienden\n- [ ] Parpadean\n- [ ] Encienden débil\n- [ ] Encienden y se apagan solas\n- [ ] Zumbido al encender\n\nTipo de luz:\n- [ ] LED panel\n- [ ] Tubo fluorescente\n- [ ] Bombillo tradicional\n- [ ] Reflector\n\n¿Es área crítica (baño, escalera, parqueadero nocturno)?\n- [ ] Sí\n- [ ] No", TicketImpact::Bajo, TicketUrgency::Baja],
            ['mantenimiento-servicios-generales', 'Solicitud de aseo profundo', 'Aseo especial o post-evento', "Ubicación: [piso / área]\n\nMotivo:\n- [ ] Derrame grande\n- [ ] Post-evento / reunión grande\n- [ ] Fin de obra\n- [ ] Post-pintura\n- [ ] Mantenimiento preventivo\n- [ ] Otro: [describir]\n\nAlcance requerido:\n- [ ] Pisos\n- [ ] Paredes\n- [ ] Ventanas\n- [ ] Muebles\n- [ ] Baños\n- [ ] Cocina\n\nFecha y hora preferida: [FECHA] [HORA]\n\n¿Requiere que sea fuera del horario laboral?\n- [ ] Sí (especificar horario)\n- [ ] No", TicketImpact::Bajo, TicketUrgency::Media],
            ['mantenimiento-mantenimiento-locativo', 'Traslado de mobiliario', 'Mover muebles entre áreas', "Desde:\n- Piso: [N origen]\n- Oficina: [ORIGEN]\n\nHacia:\n- Piso: [N destino]\n- Oficina: [DESTINO]\n\nMuebles a trasladar:\n- [ ] Escritorio\n- [ ] Silla(s): [cantidad]\n- [ ] Archivador\n- [ ] Estante / biblioteca\n- [ ] Mesa de reuniones\n- [ ] Otro: [describir]\n\n¿Hay equipo de cómputo encima?\n- [ ] Sí (coordinar con TI)\n- [ ] No\n\nFecha preferida: [FECHA]\nHora: [HORA]\n\n¿Requiere desensamblar muebles?\n- [ ] Sí (escritorios modulares, etc.)\n- [ ] No\n\nNota: traslados se hacen en horario laboral; si requiere fuera de horario, indicar.", TicketImpact::Bajo, TicketUrgency::Baja],

            // ── Operaciones ───────────────────────────────────────────
            ['operaciones-soporte-operativo', 'Falla en equipo de producción', 'Equipo operativo con falla', "Equipo afectado:\n- Nombre/TAG: [TAG-XXXX]\n- Ubicación: [PLANTA / ÁREA]\n- Tipo: [bomba/motor/tanque/caldera/etc]\n\nSíntoma:\n- [ ] No arranca\n- [ ] Arranca y se apaga solo\n- [ ] Vibración anormal\n- [ ] Ruido anormal\n- [ ] Temperatura alta\n- [ ] Fuga\n- [ ] Corriente alta\n- [ ] Otro: [describir]\n\nImpacto en producción:\n- [ ] Parada total\n- [ ] Reducción de capacidad (%?)\n- [ ] Calidad afectada\n- [ ] Ninguno (equipo redundante)\n\nAcción temporal tomada:\n[describir]\n\nTurno cuando ocurrió: [A/B/C] con [OPERARIO]", TicketImpact::Alto, TicketUrgency::Alta],
            ['operaciones-documentacion', 'Solicitud de actualización de PON', 'Actualizar procedimiento operativo normalizado', "Procedimiento: [CÓDIGO PON-XXX]\nTítulo: [NOMBRE DEL PON]\nVersión actual: [v.X]\n\nMotivo de actualización:\n- [ ] Cambio de equipo\n- [ ] Cambio de materia prima\n- [ ] Lección aprendida de incidente\n- [ ] Mejora propuesta\n- [ ] Cumplimiento normativo\n\nCambios propuestos:\n1. [Cambio 1]\n2. [Cambio 2]\n\nJustificación técnica: [describir]\n\n¿Afecta seguridad?\n- [ ] Sí (requiere revisión HSE)\n- [ ] No\n\n¿Afecta calidad?\n- [ ] Sí (requiere revisión Calidad)\n- [ ] No\n\nFecha propuesta de implementación: [FECHA]", TicketImpact::Medio, TicketUrgency::Media],
            ['operaciones-soporte-operativo', 'Reporte de parada no programada', 'Parada imprevista en operación', "Planta: [NOMBRE]\nÁrea: [ÁREA]\nTurno: [A/B/C]\n\nInicio de parada: [FECHA HORA]\nFin de parada: [FECHA HORA] (o 'en curso')\nDuración total: [HH:MM]\n\nCausa aparente:\n- [ ] Falla mecánica\n- [ ] Falla eléctrica\n- [ ] Falla de instrumentación\n- [ ] Falta de materia prima\n- [ ] Error de operación\n- [ ] Servicios (energía, agua, aire)\n- [ ] Otro: [describir]\n\nEquipos involucrados:\n[listar TAG-XXXX]\n\nImpacto:\n- Toneladas no producidas: [N]\n- Costo estimado: $[MONTO]\n\nAcciones ya tomadas:\n[describir]\n\nSe requiere:\n- [ ] Técnico de mantenimiento\n- [ ] Ingeniero de procesos\n- [ ] Jefe de producción\n- [ ] Proveedor externo", TicketImpact::Alto, TicketUrgency::Alta],
            ['operaciones-soporte-operativo', 'Solicitud de refuerzo de personal', 'Requerimiento extra de operario/técnico', "Planta/Área: [NOMBRE]\nTurno: [A/B/C]\nFechas requeridas: [DEL ...  AL ...]\n\nMotivo:\n- [ ] Aumento de producción\n- [ ] Cubrir incapacidad médica\n- [ ] Cubrir vacaciones\n- [ ] Parada de mantenimiento mayor\n- [ ] Proyecto especial\n- [ ] Otro\n\nPerfil requerido:\n- [ ] Operario básico\n- [ ] Operario con experiencia en [equipo]\n- [ ] Técnico mecánico\n- [ ] Técnico eléctrico\n- [ ] Supervisor\n- [ ] Ingeniero\n\nCantidad de personas: [N]\n\n¿Se cuenta con presupuesto?\n- [ ] Sí (centro de costo: [CC])\n- [ ] No, requiere aprobación", TicketImpact::Medio, TicketUrgency::Alta],
            ['operaciones-documentacion', 'Registro de producción diaria', 'Reporte del consolidado del día', "Planta: [NOMBRE]\nFecha: [FECHA]\nTurno reportante: [A/B/C]\n\nProducción:\n- Meta del día: [TONELADAS]\n- Real producido: [TONELADAS]\n- Cumplimiento: [%]\n\nConsumos:\n- Materia prima principal: [TONELADAS]\n- Energía: [KWH]\n- Agua: [M³]\n- Químicos: [lista]\n\nParadas:\n- Programadas: [HH:MM]\n- No programadas: [HH:MM]\n\nCalidad:\n- Lotes aprobados: [N]\n- Lotes rechazados: [N]\n- Reprocesos: [N]\n\nIncidentes de seguridad:\n- [ ] Ninguno\n- [ ] Casi-accidente (describir)\n- [ ] Accidente menor (describir)\n\nNovedades relevantes:\n[listar]\n\nPendientes para el siguiente turno:\n[listar]", TicketImpact::Bajo, TicketUrgency::Baja],
        ];

        foreach ($templates as $sort => [$catSlug, $name, $subject, $description, $impact, $urgency]) {
            $category = Category::where('slug', $catSlug)->first();

            TicketTemplate::updateOrCreate(
                ['name' => $name],
                [
                    'subject' => $subject,
                    'description' => $description,
                    'category_id' => $category?->id,
                    'impact' => $impact->value,
                    'urgency' => $urgency->value,
                    'is_active' => true,
                    'sort_order' => $sort,
                ],
            );
        }
    }
}
